import Home from './HomePage'
import Product from './ProductsPage'
import ProductBackend from './ProductsBackendPage'
import SingleProduct from './SingleProductPage'
import About from './AboutPage'
import Readme from './ReadmePage'
import Cart from './CartPage'
import CartHistory from './CartHistoryPage'
import Error from './ErrorPage'
import Checkout from './CheckoutPage'
import PrivateRoute from './PrivateRoute'
import AdminRoute from './AdminRoute'
import AuthWrapper from './AuthWrapper'
import Login from './LoginPage'
import Logout from './LogoutPage'
import Register from './RegisterPage'
import ChangePassword from './ChangePasswordPage'

import Admin from './AdminPage'
import AdminUser from './AdminUserPage'
import AdminProduct from './AdminProductPage'
import AdminCart from './AdminCartPage'
import AdminSingleCart from './AdminSingleCartPage'

export { Home, Product, ProductBackend, SingleProduct, About, Readme, Cart, CartHistory, Error, Checkout, PrivateRoute, AdminRoute, AuthWrapper, Login, Logout, Register, ChangePassword, Admin, AdminUser, AdminProduct, AdminCart, AdminSingleCart }
