export const SIDEBAR_OPEN = 'SIDEBAR_OPEN'
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE'
export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_FEATURED_PRODUCTS_SUCCESS = 'GET_FEATURED_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'
export const GET_SINGLE_PRODUCT_BEGIN = 'GET_SINGLE_PRODUCT_BEGIN'
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS'
export const GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLE_PRODUCT_ERROR'

export const GET_FILTER_BEGIN = 'GET_FILTER_BEGIN'
export const GET_FILTER_SUCCESS = 'GET_FILTER_SUCCESS'
export const GET_FILTER_ERROR = 'GET_FILTER_ERROR'
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const SET_GRIDVIEW = 'SET_GRIDVIEW'
export const SET_LISTVIEW = 'SET_LISTVIEW'
export const UPDATE_SORT = 'UPDATE_SORT'
export const SORT_PRODUCTS = 'SORT_PRODUCTS'
export const UPDATE_FILTERS = 'UPDATE_FILTERS'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const TOGGLE_CART_ITEM_AMOUNT = 'TOGGLE_CART_ITEM_AMOUNT'
export const CLEAR_CART = 'CLEAR_CART'
export const COUNT_CART_TOTALS = 'COUNT_CART_TOTALS'

export const LOAD_ROOMS = 'LOAD_ROOMS'
export const GET_SINGLE_ROOM_BEGIN = 'GET_SINGLE_ROOM_BEGIN'
export const GET_SINGLE_ROOM_SUCCESS = 'GET_SINGLE_ROOM_SUCCESS'
export const GET_SINGLE_ROOM_ERROR = 'GET_SINGLE_ROOM_ERROR'
export const GET_ALL_ROOMS_LOADING = 'GET_ALL_ROOMS_LOADING'
export const GET_ALL_ROOMS_SUCCESS = 'GET_ALL_ROOMS_SUCCESS'
export const GET_ALL_ROOMS_ERROR = 'GET_ALL_ROOMS_ERROR'

export const CREATE_BOOKING = 'CREATE_BOOKING'
export const CLEAR_BOOKING = 'CLEAR_BOOKING'
export const UPDATE_BOOKING = 'UPDATE_BOOKING'
export const BOOKING_SUBMIT_BEGIN = 'BOOKING_SUBMIT_BEGIN'
export const BOOKING_SUBMIT_SUCCESS = 'BOOKING_SUBMIT_SUCCESS'
export const BOOKING_SUBMIT_ERROR = 'BOOKING_SUBMIT_ERROR'

export const SET_CURRENT_USER_BOOKINGS = 'SET_CURRENT_USER_BOOKINGS'
export const SET_CURRENT_USER_BOOKINGS_LOADING = 'SET_CURRENT_USER_BOOKINGS_LOADING'
export const SET_CURRENT_USER_BOOKINGS_ERROR = 'SET_CURRENT_USER_BOOKINGS_ERROR'
export const SET_BOOKING_ALERT = 'SET_BOOKING_ALERT'

export const SET_ALERT = 'SET_ALERT'

// Admin User
export const SET_ALL_USERS_LOADING = 'SET_ALL_USERS_LOADING'
export const SET_ALL_USERS_SUCCESS = 'SET_ALL_USERS_SUCCESS'
export const SET_ALL_USERS_ERROR = 'SET_ALL_USERS_ERROR'
export const UPDATE_USER_FORM = 'UPDATE_USER_FORM'

// Admin Product
export const SET_ALL_PRODUCTS_LOADING = 'SET_ALL_PRODUCTS_LOADING'
export const SET_ALL_PRODUCTS_SUCCESS = 'SET_ALL_PRODUCTS_SUCCESS'
export const SET_ALL_PRODUCTS_ERROR = 'SET_ALL_PRODUCTS_ERROR'



export const CLEAR_FORM = 'CLEAR_FORM'
export const ADD_USER = 'ADD_USER'
export const SET_SUBMIT_SUCCESS = 'SET_SUBMIT_SUCCESS'
export const UPDATE_ACTION_STATE = 'UPDATE_ACTION_STATE'
export const UPDATE_FORM = 'UPDATE_FORM'
export const SET_FORM = 'SET_FORM'
export const SET_ACTION_STATE = 'SET_ACTION_STATE'
export const SET_ACTION_ID = 'SET_ACTION_ID'
export const SET_ACTION_OBJECT = 'SET_ACTION_OBJECT'
export const SET_ACTION = 'SET_ACTION'
export const SET_LOADING = 'SET_LOADING'
export const SET_SUCCESS = 'SET_SUCCESS'
export const SET_ERROR = 'SET_ERROR'
export const GET_SINGLE_OBJECT = 'GET_SINGLE_OBJECT'
export const GET_SINGLE_OBJECT_LOADING = 'GET_SINGLE_OBJECT_LOADING'
export const GET_SINGLE_OBJECT_ERROR = 'GET_SINGLE_OBJECT_ERROR'






